export const GET_JOKES = "GET_JOKES";
export const GET_JOKES_FULFILLED = "GET_JOKES_FULFILLED";
export const GET_JOKES_REJECTED = "GET_JOKES_REJECTED";
export const GET_JOKES_PENDING = "GET_JOKES_PENDING";
export const GET_PREVIOUS_JOKES = "GET_PREVIOUS_JOKES";
export const REACT_ON_JOKES = "REACT_ON_JOKES";
export const GO_TO_NEXT_JOKE = "GO_TO_NEXT_JOKE";
export const GET_SUMMARY = "GET_SUMMARY";
